events {}

http {
    server {
        listen 80;
        server_name project-banana.com www.project-banana.com app.project-banana.com project-banana.ddns.net;

        location / {
            proxy_pass http://server:8080;
        }

        location /test {
            add_header Content-Type text/plain;
            return 200 "hello world from production\n";
        }
    }

    server {
        listen 80;
        server_name project-banana.dev www.project-banana.dev app.project-banana.dev; 

        location / {
            add_header Content-Type text/plain;
            return 200 "hello!";
        }
    }
}
