events {}

http {
    server {
        listen 80;
        server_name project-banana.com www.project-banana.com app.project-banana.com; 

        location / {
            proxy_pass http://pb-proxy:8080;
            proxy_set_header Host $host;
        }

        location /hello {
            add_header Content-Type text/plain;
            return 200 "hello world from production!";
        }
    }

    server {
        listen 80;
        server_name project-banana.dev www.project-banana.dev app.project-banana.dev; 

        location / {
            proxy_pass http://pb-proxy:8080;
            proxy_set_header Host $host;
        }

        location /hello {
            add_header Content-Type text/plain;
            return 200 "hello world from staging!";
        }
    }
}
